# Global values for each entry, if not overridden:
Global Values:
 Encoding: "UTF-8"
 Version: "1.0"
 Type: "Application"
 Terminal: "false"
 Categories: "Games;sSwine;"
 Icon: "global_icon.png"
 Path: "global/path"
 Hidden: "false"
 NoDisplay: "false"

# Entry-specific info, which overrides Global Values: 
Game Name:
 Exec: "wine lol.exe"
 Icon: "entry_icon.png"

